Fix "no extractor found" exception.
os.path.abspath can't handle a None object, causing the script to break
with an even more unhelpful exception than the one given just a line
later with `essentia_path` set to `None`.

```
Traceback (most recent call last):
  File "./abzsubmit", line 11, in <module>
    from abz import acousticbrainz
  File ".../acousticbrainz-client/abz/acousticbrainz.py", line 23, in <module>
    config.load_settings()
  File ".../acousticbrainz-client/abz/config.py", line 98, in load_settings
    essentia_path =
os.path.abspath(distutils.spawn.find_executable(essentia))
  File ".../venv/lib/python3.4/posixpath.py", line 357, in abspath
    if not isabs(path):
  File ".../venv/lib/python3.4/posixpath.py", line 63, in isabs
    return s.startswith(sep)
AttributeError: 'NoneType' object has no attribute 'startswith'
```